# Compiler and linker options
CC := gcc
LD := ld
NASM := nasm
CFLAGS := -m32 -ffreestanding -std=c99 -Wall -Wextra
LDFLAGS := -m elf_i386 -T ./src/link.ld

# Directories
SRCDIR := ./src
OBJDIR := ./obj
BINDIR := ./boot

# Source files
ASM := $(* $(SRCDIR)/*.asm)
SRC := $(* $(SRCDIR)/**/*.c)
ASMOBJ := $(* $(SRCDIR)/%.asm,$(OBJDIR)/%.o,$(ASM))
COBJ := $(* $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(SRC))

# Targets
TARGET := $(BINDIR)/kernel.bin

# Phony targets
.PHONY: all clean

# Default target
all: $(TARGET)

# Compile assembly files
$(OBJDIR)/%.o: $(SRCDIR)/%.asm
    $(NASM) -f elf32 $< -o $@

# Compile C files
$(OBJDIR)/%.o: $(SRCDIR)/%.c
    $(CC) $(CFLAGS) -c $< -o $@

# Link object files
$(TARGET): $(ASMOBJ) $(COBJ)
    $(LD) $(LDFLAGS) -o $@ $^

# Clean up
clean:
    rm -f $(OBJDIR)/*.o
    rm -f $(TARGET)
